runtime: nodejs20

handlers:
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|json|svg|woff|woff2|ttf|eot))
    static_files: build/\1
    upload: build/.*\.(js|css|png|jpg|jpeg|gif|ico|json|svg|woff|woff2|ttf|eot)

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
